%%{init: {'theme': 'default', 'themeVariables': { 'background': '#FFFFFF' }}}%%
flowchart LR
    A[GitHub]:::icon
    B[Парсер]:::icon
    D[Предобработка]:::icon
    F[CodeT5]:::icon
    I[Генерация]:::icon
    J[GUI]:::icon
    K[Пользователь]:::icon

    C[(CodeSearchNet)]:::db
    E[(Датасет)]:::db
    H[(Модель)]:::db

    A --> B
    B --> D
    C --> D
    D --> E
    E --> F
    G[Hyperparams] --> F
    F --> H
    H --> I
    I --> J
    K <--> J

    classDef db fill:#ffffff,stroke:#1565c0,stroke-width:2px,color:#000000,font-weight:bold;
    classDef icon fill:#ffffff,stroke:#495057,stroke-width:1.5px,color:#212529,font-weight:600;


    class C,E,H db
    class A,B,D,F,I,J,K icon